import { readFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, "../data");

// topics.json is generated by `npm run sync-topics`
// Each entry: { key, label, icon }
const manifest = JSON.parse(
  readFileSync(join(DATA_DIR, "topics.json"), "utf8")
);

// Load question data for each topic in the manifest
const allQuestions = {};
for (const { key } of manifest) {
  try {
    const raw = readFileSync(join(DATA_DIR, `questions_${key}.json`), "utf8");
    allQuestions[key] = JSON.parse(raw);
  } catch (err) {
    console.warn(`[Questions] Failed to load "${key}": ${err.message}`);
  }
}

// Exported as full objects so the client receives label + icon without hardcoding
export const TOPICS = manifest.filter((t) => allQuestions[t.key]);

console.log(
  `[Questions] Loaded topics: ${TOPICS.map((t) => t.key).join(", ")}`
);

function shuffle(arr) {
  const out = [...arr];
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

// Convert JSON format → internal game format
function toGameFormat(q) {
  const keys = ["A", "B", "C", "D"];
  return {
    id: q.id,
    text: q.question,
    answers: keys.map((k) => q.options[k]),
    correctIndex: keys.indexOf(q.correct_answer),
  };
}

/**
 * Returns 10 shuffled questions for a single topic + difficulty.
 */
export function getQuestions(topicKey, difficulty) {
  const pool = allQuestions[topicKey]
    .filter((q) => q.difficulty === difficulty)
    .map(toGameFormat);
  return shuffle(pool).slice(0, 10);
}

/**
 * Returns 15 questions in escalating difficulty: 5 easy → 5 medium → 5 hard.
 */
export function getIncreasingDifficultyQuestions(topicKey) {
  const result = [];
  for (const diff of ["easy", "medium", "hard"]) {
    const pool = allQuestions[topicKey]
      .filter((q) => q.difficulty === diff)
      .map(toGameFormat);
    result.push(...shuffle(pool).slice(0, 5));
  }
  return result;
}

/**
 * Picks a random topic key and returns its questions.
 */
export function getRandomTopicQuestions(difficulty, mode) {
  const keys = TOPICS.map((t) => t.key);
  const topicKey = keys[Math.floor(Math.random() * keys.length)];
  const questions =
    mode === "increasing"
      ? getIncreasingDifficultyQuestions(topicKey)
      : getQuestions(topicKey, difficulty);
  return { topic: topicKey, questions };
}
